using System.Text.Json;
using System.Text.Json.Serialization;

namespace Mona.Core.Calendar;

/// <summary>
/// Where every calendar piece goes — looked up, not computed.
///
/// The typesetting rules behind the design — per-glyph scale and shift, the
/// spacing floor that stops a wide month crashing into the day, the weather icon
/// hanging off the weekday tab — are not evaluated at runtime. They were worked
/// out once, offline, and the answer for every combination was written into this
/// table; the renderer looks a row up and composites what it says.
///
/// That is affordable because the arrangements are countable: twelve months by
/// thirty-one days for the date, plus the weekday tab, the time-of-day card and
/// the weather icon, is a couple of thousand rows and a couple of hundred
/// kilobytes. And it means the layout cannot drift away from the artwork it was
/// measured against, which is what re-deriving it in code would eventually do.
///
/// The table and the artwork are one deliverable: the numbers refer to specific
/// pieces at specific sizes, so replacing either on its own takes the sticker
/// apart. It is not meant to be reformatted or regenerated by hand.
/// </summary>
public sealed class CalendarLayout
{
    /// <summary>
    /// One placed piece. <c>A</c> is <c>[a, b, c, d, tx, ty]</c> and reads
    /// <c>canvas = A · assetPixel + T</c>, in the layout's own canvas; scale the
    /// whole six by <c>renderWidth / canvasWidth</c> to draw at any size.
    /// </summary>
    public sealed class Entry
    {
        [JsonPropertyName("a")] public double[] A { get; set; } = [];
        /// <summary>Flat asset prefix, e.g. <c>cal-day-7</c>; the layer suffix goes on the end.</summary>
        [JsonPropertyName("g")] public string G { get; set; } = "";
        /// <summary>
        /// Only the weather carries one: the four corners of the slanted white
        /// square it sits on, in canvas coordinates.
        /// </summary>
        [JsonPropertyName("card")] public double[][]? Card { get; set; }

        public double[] Matrix => A.Length >= 6 ? A : [1, 0, 0, 1, 0, 0];
    }

    /// <summary>
    /// One of the design's five layers, bottom first. A layer is one colour all
    /// through — that is the premise the whole stacking rests on.
    /// </summary>
    public sealed class Layer
    {
        [JsonPropertyName("white")] public bool White { get; set; }
        /// <summary><c>[element, part]</c>, e.g. <c>["day_0", "plate"]</c>.</summary>
        [JsonPropertyName("items")] public string[][] Items { get; set; } = [];
    }

    public sealed class PlacementTable
    {
        /// <summary>Keyed <c>"&lt;month&gt;-&lt;day&gt;"</c>.</summary>
        [JsonPropertyName("date")]
        public Dictionary<string, Dictionary<string, Entry>> Date { get; set; } = new();
        /// <summary>Keyed <c>"&lt;d1|d2&gt;|&lt;weekday&gt;"</c>.</summary>
        [JsonPropertyName("week")]
        public Dictionary<string, Entry> Week { get; set; } = new();
        /// <summary>Keyed <c>"&lt;d1|d2&gt;|&lt;slot&gt;"</c>.</summary>
        [JsonPropertyName("status")]
        public Dictionary<string, Entry> Status { get; set; } = new();
        /// <summary>
        /// Keyed <c>"&lt;d1|d2&gt;|&lt;weekday&gt;|&lt;kind&gt;|&lt;frame&gt;"</c> — the icon
        /// hangs off the weekday tab, so which weekday it is changes where it lands.
        /// </summary>
        [JsonPropertyName("weather")]
        public Dictionary<string, Entry> Weather { get; set; } = new();
    }

    [JsonPropertyName("canvas")] public double[] Canvas { get; set; } = [683, 557];
    [JsonPropertyName("assets")] public string[] Assets { get; set; } = [];
    [JsonPropertyName("stack")] public Layer[] Stack { get; set; } = [];
    /// <summary>part name → file suffix, e.g. <c>plate</c> → <c>-plate</c>.</summary>
    [JsonPropertyName("suffix")] public Dictionary<string, string> Suffix { get; set; } = new();
    /// <summary>
    /// Radius that bridges the month's black to the day's black, in canvas
    /// pixels. Absolute rather than a fraction of the width, because the canvas
    /// was widened to stop two-digit months running off the left and the bridge
    /// should not have widened with it.
    /// </summary>
    [JsonPropertyName("bridge_px")] public double BridgePx { get; set; } = 19.2;
    /// <summary>
    /// Square brush that seals the hairline between neighbouring plates: wider
    /// under the whites, where the gap between the weather card and the weekday
    /// tab is a good two pixels, narrower under the blacks so the narrow white
    /// slots the design does want stay open.
    /// </summary>
    [JsonPropertyName("seal")] public Dictionary<string, int> Seal { get; set; } = new();
    [JsonPropertyName("placements")] public PlacementTable Placements { get; set; } = new();

    public double CanvasWidth => Canvas.Length > 0 ? Canvas[0] : 683;
    public double CanvasHeight => Canvas.Length > 1 ? Canvas[1] : 557;
    public double Aspect => CanvasWidth / CanvasHeight;

    public static CalendarLayout? Load(string path)
    {
        if (!File.Exists(path)) return null;
        using var stream = File.OpenRead(path);
        return JsonSerializer.Deserialize<CalendarLayout>(stream, Options);
    }

    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNameCaseInsensitive = false,
        ReadCommentHandling = JsonCommentHandling.Skip
    };
}
